version: '3.4'

services:
  server:
    container_name: makerspace_server
    image: server
    depends_on:
      - db
    build:
      context: server
      dockerfile: ./Dockerfile
      target: production
    volumes:
      - ./server:/home/node/app/src
    expose:
      - '3000'
    ports:
      - 3000:3000
    command: npm run start && npm run knex:migrate:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  db:
    image: postgres
    container_name: makerspace_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  testdb:
    image: postgres
    container_name: test_db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
