name: Backend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, heroku-deploy]
    paths: ["server/**", "package.json", "package-lock.json"]
  pull_request:
    branches: [main, heroku-deploy]
    paths: ["server/**", "package.json", "package-lock.json"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5433:5432
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpassword
          POSTGRES_DB: pgdb

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.ATRIUM_INTEGRATION_ACCESS_SSH_KEY}}
          submodules: recursive
          
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: package-lock.json
          

      - name: Install Node modules
        run: npm ci
      - name: Install Client Node Modules
        run: cd client && npm ci
      - name: Lint Server
        run: npm run lint
        # Don't fail build on errors (bc the entire build would fail rn)
        # if its 2026 and this is still here you should feel bad  
        continue-on-error: true
      - name: Run Knex migrations
        run: npm run build:server && npm run knex:migrate:latest DEBUG=knex:tx
        env:
          DATABASE_URL: postgresql://pguser:pgpassword@localhost:5433/pgdb
          NODE_ENV: "development"
